name: kira-flow

services:
  app:
    image: ${DOCKER_USERNAME:-local}/kira-flow:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - "3019:3019"
    restart: unless-stopped
